### ISSUE TITLE
Feature request: pymata4 wrapper code for addressing DC motors

### ISSUE THREAD

**Issue by Runtime-Learner** [MrYsLab/pymata4#38]
I am controlling DC motors using an L298d motor driver and an arduino board

Python scripts would be more readable if pymata4 objects had an editable list of DC motors linked to arduino pins (e.g: pin1, pin2, PWM pin). I believe that being able to address DC motors directly (e.g: rotate clockwise at 100% speed) instead of having to  write to individual pins would make scripts more readable and reusable.

**Comment by MrYsLab** [comment]
@Runtime-Learner  
Hi, and thanks for the feature request. The pymata4 API was designed to be general-purpose and not for any specific application. The intent is for the application developer to use pymata4 to build their own application-specific API using its low-level features.
I agree with you that having a motor controller API would make the application easier to write and understand. 
What I would suggest is that you craft your own library. If you would like to see an example of doing so, you can [view the code I wrote to control a robot's motors](https://github.com/MrYsLab/microbit-robot/blob/master/robot/microbit_robot.py). This does not use pymata4 and is written in MicroPython, but hopefully should give you an idea of how to write your own. 
If you need any guidance, I would be happy to help.
Also, I would suggest you consider using Telemetrix instead of pymata4. You can view its [API](https://htmlpreview.github.io/?https://github.com/MrYsLab/telemetrix/blob/master/html/telemetrix/index.html) and see that it offers many more features than pymata4. A [user's guide ](https://mryslab.github.io/telemetrix/)is also available.

I am closing this issue, but if you feel it should be reopened, please leave a comment here, and I will see it.
Thanks.
